### ISSUE TITLE
[grpc-haskell-core] Compilation error with gRPC 1.27.1 

### ISSUE THREAD

**Issue by avanov** [awakesecurity/gRPC-haskell#103]
Hi!

Below is the environment that fails to build `grpc-haskell-core` against `gRPC 1.27.1` (MacOS Catalina)

Nix shell:
```
{ pkgs ? import (builtins.fetchGit {
    # https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs

    # Descriptive name to make the store path easier to identify
    name = "nixpkgs-2020-02-22";

    url = https://github.com/NixOS/nixpkgs-channels/;

    # Commit hash for nixos-unstable as of 2020-01-06
    # `git ls-remote https://github.com/nixos/nixpkgs-channels nixos-unstable`
    # or
    # `git ls-remote https://github.com/nixos/nixpkgs master`
    ref = "refs/heads/nixpkgs-unstable";

    rev = "f098b0dd2cdc008711938272b3d622cb55131706";
}) {}}:

with pkgs;

let
    haskellTools = haskell.packages.ghc865.ghcWithPackages (
        haskellPkgs: with haskellPkgs; [
            # tools
            cabal-install
        ]
    );

in

mkShell {
    buildInputs = [
        haskellTools
        zlib
        grpc
    ];
}
```

A cabal project that depends on `grpc-haskell ^>= 0.0.1.0` fails at build:
```
cabal v2-build all
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - grpc-haskell-core-0.0.0.0 (lib) (requires build)
 - grpc-haskell-0.0.1.0 (lib) (requires build)
Starting     grpc-haskell-core-0.0.0.0 (lib)
Building     grpc-haskell-core-0.0.0.0 (lib)

Failed to build grpc-haskell-core-0.0.0.0.
Build log (
/Users/ghostwriter/.cabal/logs/ghc-8.6.5/grpc-hskll-cr-0.0.0.0-73aa3bef.log ):
Configuring library for grpc-haskell-core-0.0.0.0..
Preprocessing library for grpc-haskell-core-0.0.0.0..
Building library for grpc-haskell-core-0.0.0.0..
[ 1 of 21] Compiling Network.GRPC.Unsafe.ChannelArgs ( dist/build/Network/GRPC/Unsafe/ChannelArgs.hs, dist/build/Network/GRPC/Unsafe/ChannelArgs.o )
[ 2 of 21] Compiling Network.GRPC.Unsafe.Constants ( dist/build/Network/GRPC/Unsafe/Constants.hs, dist/build/Network/GRPC/Unsafe/Constants.o )
[ 3 of 21] Compiling Network.GRPC.Unsafe.Slice ( dist/build/Network/GRPC/Unsafe/Slice.hs, dist/build/Network/GRPC/Unsafe/Slice.o )
[ 4 of 21] Compiling Network.GRPC.Unsafe.Metadata ( dist/build/Network/GRPC/Unsafe/Metadata.hs, dist/build/Network/GRPC/Unsafe/Metadata.o )
[ 5 of 21] Compiling Network.GRPC.Unsafe.ByteBuffer ( dist/build/Network/GRPC/Unsafe/ByteBuffer.hs, dist/build/Network/GRPC/Unsafe/ByteBuffer.o )
[ 6 of 21] Compiling Network.GRPC.Unsafe.Op ( dist/build/Network/GRPC/Unsafe/Op.hs, dist/build/Network/GRPC/Unsafe/Op.o )
[ 7 of 21] Compiling Network.GRPC.Unsafe.Time ( dist/build/Network/GRPC/Unsafe/Time.hs, dist/build/Network/GRPC/Unsafe/Time.o )
[ 8 of 21] Compiling Network.GRPC.Unsafe ( dist/build/Network/GRPC/Unsafe.hs, dist/build/Network/GRPC/Unsafe.o )
[ 9 of 21] Compiling Network.GRPC.Unsafe.Security ( dist/build/Network/GRPC/Unsafe/Security.hs, dist/build/Network/GRPC/Unsafe/Security.o )
ld: warning: /nix/store/342k9dbmxlvzd6wksjcv0hgqyfgj3q2k-libiconv-osx-10.12.6/lib/libiconv.dylib, ignoring unexpected dylib file
ld: warning: /nix/store/342k9dbmxlvzd6wksjcv0hgqyfgj3q2k-libiconv-osx-10.12.6/lib/libiconv.dylib, ignoring unexpected dylib file
[10 of 21] Compiling Network.GRPC.LowLevel.GRPC ( src/Network/GRPC/LowLevel/GRPC.hs, dist/build/Network/GRPC/LowLevel/GRPC.o )
[11 of 21] Compiling Network.GRPC.LowLevel.CompletionQueue.Internal ( src/Network/GRPC/LowLevel/CompletionQueue/Internal.hs, dist/build/Network/GRPC/LowLevel/CompletionQueue/Internal.o )
[12 of 21] Compiling Network.GRPC.LowLevel.Call ( src/Network/GRPC/LowLevel/Call.hs, dist/build/Network/GRPC/LowLevel/Call.o )
[13 of 21] Compiling Network.GRPC.LowLevel.CompletionQueue ( src/Network/GRPC/LowLevel/CompletionQueue.hs, dist/build/Network/GRPC/LowLevel/CompletionQueue.o )
[14 of 21] Compiling Network.GRPC.LowLevel.Op ( src/Network/GRPC/LowLevel/Op.hs, dist/build/Network/GRPC/LowLevel/Op.o )
[15 of 21] Compiling Network.GRPC.LowLevel.Server ( src/Network/GRPC/LowLevel/Server.hs, dist/build/Network/GRPC/LowLevel/Server.o )
[16 of 21] Compiling Network.GRPC.LowLevel.Client ( src/Network/GRPC/LowLevel/Client.hs, dist/build/Network/GRPC/LowLevel/Client.o )
[17 of 21] Compiling Network.GRPC.LowLevel.Call.Unregistered ( src/Network/GRPC/LowLevel/Call/Unregistered.hs, dist/build/Network/GRPC/LowLevel/Call/Unregistered.o )
[18 of 21] Compiling Network.GRPC.LowLevel.CompletionQueue.Unregistered ( src/Network/GRPC/LowLevel/CompletionQueue/Unregistered.hs, dist/build/Network/GRPC/LowLevel/CompletionQueue/Unregistered.o )
[19 of 21] Compiling Network.GRPC.LowLevel.Server.Unregistered ( src/Network/GRPC/LowLevel/Server/Unregistered.hs, dist/build/Network/GRPC/LowLevel/Server/Unregistered.o )
[20 of 21] Compiling Network.GRPC.LowLevel.Client.Unregistered ( src/Network/GRPC/LowLevel/Client/Unregistered.hs, dist/build/Network/GRPC/LowLevel/Client/Unregistered.o )
[21 of 21] Compiling Network.GRPC.LowLevel ( src/Network/GRPC/LowLevel.hs, dist/build/Network/GRPC/LowLevel.o )

cbits/grpc_haskell.c:533:68: error:
     error: too few arguments to function call, expected 3, have 2
      return grpc_metadata_credentials_create_from_plugin(*plugin, NULL);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ^
    |
533 |   return grpc_metadata_credentials_create_from_plugin(*plugin, NULL);
    |                                                                    ^

/nix/store/53w3nv38xc2y3254ayz3ww2xy7nmxq5n-grpc-1.27.1/include/grpc/grpc_security.h:440:9: error:
     note: 'grpc_metadata_credentials_create_from_plugin' declared here
    |
440 | GRPCAPI grpc_call_credentials* grpc_metadata_credentials_create_from_plugin(
    |         ^
GRPCAPI grpc_call_credentials* grpc_metadata_credentials_create_from_plugin(
        ^
1 error generated.
`cc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Failed to build grpc-haskell-core-0.0.0.0
```

**Comment by avanov** [comment]
Amazingly enough, it compiles with `grpc-1.26.0`. Here's the updated nix shell
```
{ pkgs ? import (builtins.fetchGit {
    # https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs

    # Descriptive name to make the store path easier to identify
    name = "nixpkgs-2020-02-22";

    url = https://github.com/NixOS/nixpkgs-channels/;

    # Commit hash for nixos-unstable as of 2020-01-06
    # `git ls-remote https://github.com/nixos/nixpkgs-channels nixos-unstable`
    # or
    # `git ls-remote https://github.com/nixos/nixpkgs master`
    ref = "refs/heads/nixpkgs-unstable";

    rev = "f098b0dd2cdc008711938272b3d622cb55131706";
}) {}}:

with pkgs;

let
    haskellTools = haskell.packages.ghc865.ghcWithPackages (
        haskellPkgs: with haskellPkgs; [
            # tools
            cabal-install
        ]
    );

    # https://github.com/grpc/grpc/releases/tag/v1.2.5
    # https://github.com/awakesecurity/gRPC-haskell/blob/595cb6a3bfbc50348af44d4bbd981ba0c02e45dd/README.md#installation
    # https://github.com/awakesecurity/gRPC-haskell/issues/103
    supportedGrpc = grpc.overrideAttrs (oldAttrs: rec {
        version = "1.26.0";
        src = builtins.fetchGit {
            name = "grpc-${version}";
            url = https://github.com/grpc/grpc/;
            ref = "refs/tags/v${version}";
            rev = "de893acb6aef88484a427e64b96727e4926fdcfd";
        };
        patches = [];
    });

in

mkShell {
    buildInputs = [
        haskellTools
        zlib
        supportedGrpc
    ];
}
```

**Comment by tmcgilchrist** [comment]
Hi @avanov, Looking at the git history the method `grpc_metadata_credentials_create_from_plugin` added an extra argument in the 1.27 release https://github.com/grpc/grpc/commit/e10d90ba274146eab5dc1073e0675fef07ef26ce

To fix this issue it would require updating the cbits and handling this change.
Is it possible to upgrade this project to use a newer version of grpc?

**Comment by cocreature** [comment]
We already have the patch for this in https://github.com/digital-asset/daml/blob/main/bazel_tools/grpc-haskell-core-upgrade.patch. Just didn’t find the time to turn it into a PR so far.

**Comment by Gabriel439** [comment]
For people following this issue #117 is upgrading the gRPC library

**Comment by tmcgilchrist** [comment]
This issue has been closed via https://github.com/awakesecurity/gRPC-haskell/pull/117

**Comment by avanov** [comment]
thanks!
